prefix xsd:        <http://www.w3.org/2001/XMLSchema#>
prefix rdfs:       <http://www.w3.org/2000/01/rdf-schema#>
prefix dcterms:    <http://purl.org/dc/terms/>
prefix void:       <http://rdfs.org/ns/void#>
prefix nfo:        <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
prefix frbr:       <http://purl.org/vocab/frbr/core#>
prefix irw:        <http://www.ontologydesignpatterns.org/ont/web/irw.owl#>
prefix conversion: <http://purl.org/twc/vocab/conversion/>
prefix frir:       <http://purl.org/twc/ontology/frir.owl#>
prefix prov:       <http://dvcs.w3.org/hg/prov/file/tip/ontology/ProvenanceOntology.owl#>

ASK
WHERE {
   GRAPH ?g {
      ?anything nfo:hasHash <hash:SHA256-0> .
   }
}
