prefix xsd:        <http://www.w3.org/2001/XMLSchema#>
prefix rdfs:       <http://www.w3.org/2000/01/rdf-schema#>
prefix dcterms:    <http://purl.org/dc/terms/>
prefix void:       <http://rdfs.org/ns/void#>
prefix irw:        <http://www.ontologydesignpatterns.org/ont/web/irw.owl#>
prefix conversion: <http://purl.org/twc/vocab/conversion/>
prefix frir:       <http://purl.org/twc/ontology/frir.owl#>
prefix prov:       <http://dvcs.w3.org/hg/prov/file/tip/ontology/ProvenanceOntology.owl#>
prefix frbrcore: <http://purl.org/vocab/frbr/core#>

ASK
WHERE {
   GRAPH ?g {
      ?item a frbrcore:Item;                     
         dcterms:date        ?recentdate;     
         frbrcore:exemplarOf ?manifestation . 
      optional { 
         ?item dcterms:date ?otherdate . 
         filter(?otherdate < ?mindate) 
      }
      filter ( !bound(?otherdate) )

      ?manifestation a frbrcore:Manifestation;   
         frbrcore:embodimentOf ?expression .  

      ?expression a frbrcore:Expression;         
         frbrcore:realizationOf ?work .       

      ?work a frbrcore:Work .                    
   }
}
