PREFIX ov:  <http://open.vocab.org/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
ASK
WHERE {
   GRAPH ?g {
      <http://logd.tw.rpi.edu/id/us/fed/agency/Has_Space_2/Has_Space_1> ov:csvRow "2"^^xsd:integer .
   }
}
